{{/* Generate analyzer deployment */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blackpoint.fullname" . }}-analyzer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
    tier.blackpoint.com/name: gold
  annotations:
    {{- include "blackpoint.annotations" . | nindent 4 }}
    security.blackpoint.com/encryption-required: "true"
    security.blackpoint.com/last-scan: {{ now | date "2006-01-02" | quote }}
spec:
  replicas: {{ .Values.analyzer.replicaCount }}
  selector:
    matchLabels:
      {{- include "blackpoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: analyzer
  template:
    metadata:
      labels:
        {{- include "blackpoint.labels" . | nindent 8 }}
        app.kubernetes.io/component: analyzer
        tier.blackpoint.com/name: gold
      annotations:
        {{- include "blackpoint.annotations" . | nindent 8 }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      {{- include "blackpoint.podSecurityContext" . | nindent 6 }}
      serviceAccountName: {{ include "blackpoint.serviceAccountName" . }}
      containers:
        - name: analyzer
          image: "{{ .Values.global.image.registry }}/analyzer:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- include "blackpoint.containerSecurityContext" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            {{- toYaml .Values.analyzer.resources | nindent 12 }}
          env:
            {{- include "blackpoint.commonEnvVars" . | nindent 12 }}
            - name: ANALYZER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "blackpoint.fullname" . }}-analyzer-config
                  key: config.yaml
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "blackpoint.fullname" . }}-analyzer-secrets
                  key: encryption-key
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: certs
              mountPath: /etc/certs
              readOnly: true
            - name: config
              mountPath: /etc/analyzer
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: certs
          secret:
            secretName: {{ include "blackpoint.fullname" . }}-analyzer-certs
        - name: config
          configMap:
            name: {{ include "blackpoint.fullname" . }}-analyzer-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "blackpoint.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: analyzer
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "blackpoint.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: analyzer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-analyzer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
  annotations:
    {{- include "blackpoint.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.analyzer.service.type }}
  ports:
    - port: {{ .Values.analyzer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.analyzer.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "blackpoint.fullname" . }}-analyzer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: analyzer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "blackpoint.fullname" . }}-analyzer
  minReplicas: {{ .Values.analyzer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analyzer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analyzer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.analyzer.autoscaling.targetMemoryUtilizationPercentage }}
    {{- if .Values.global.monitoring.metrics.custom.eventProcessingRate }}
    - type: Pods
      pods:
        metric:
          name: event_processing_rate
        target:
          type: AverageValue
          averageValue: 1000
    {{- end }}