{{/* Normalizer Deployment Template */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blackpoint.fullname" . }}-normalizer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: normalizer
    tier.blackpoint.com/name: silver
spec:
  replicas: {{ .Values.normalizer.replicaCount }}
  selector:
    matchLabels:
      {{- include "blackpoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: normalizer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "blackpoint.labels" . | nindent 8 }}
        app.kubernetes.io/component: normalizer
      annotations:
        {{- include "blackpoint.annotations" . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/normalizer-configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- include "blackpoint.podSecurityContext" . | nindent 8 }}
      containers:
        - name: normalizer
          image: "{{ .Values.global.image.registry }}/normalizer:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          securityContext:
            {{- include "blackpoint.containerSecurityContext" . | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.normalizer.resources | nindent 12 }}
          env:
            {{- include "blackpoint.commonEnvVars" . | nindent 12 }}
            - name: BUFFER_SIZE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "blackpoint.fullname" . }}-normalizer-config
                  key: buffer.size
            - name: BUFFER_FLUSH_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "blackpoint.fullname" . }}-normalizer-config
                  key: buffer.flushInterval
            - name: MAX_PROCESSING_TIME
              value: "5000" # 5 seconds max processing time per event
            - name: MIN_REPLICAS
              value: "3"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        {{- toYaml .Values.normalizer.affinity | nindent 8 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "blackpoint.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: normalizer

---
{{/* Normalizer Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-normalizer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: normalizer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: normalizer

---
{{/* Normalizer ServiceMonitor for Prometheus monitoring */}}
{{- if .Values.global.monitoring.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blackpoint.fullname" . }}-normalizer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: normalizer
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.global.monitoring.prometheus.scrapeInterval }}
      path: /metrics
      scheme: http
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: '^(normalizer_events_processed_total|normalizer_processing_duration_seconds|normalizer_errors_total).*'
          action: keep
  selector:
    matchLabels:
      {{- include "blackpoint.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: normalizer
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}

---
{{/* Normalizer HorizontalPodAutoscaler */}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "blackpoint.fullname" . }}-normalizer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
    app.kubernetes.io/component: normalizer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "blackpoint.fullname" . }}-normalizer
  minReplicas: {{ .Values.normalizer.replicaCount }}
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60