{{/* Generate Kubernetes Secrets for BlackPoint Security Integration Framework */}}

{{/* OAuth2.0 Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackpoint.fullname" . }}-oauth-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    encryption.blackpoint.io/kms-key: alias/blackpoint-secrets
    secret.blackpoint.io/rotation-schedule: {{ .Values.global.security.secretRotation.schedule }}
    secret.blackpoint.io/last-rotated: {{ .Values.global.security.secretRotation.lastRotated }}
    audit.blackpoint.io/enabled: "true"
    monitoring.blackpoint.io/alert-on-access: "true"
type: Opaque
data:
  client_id: {{ .Values.global.security.oauth.clientId | b64enc }}
  client_secret: {{ .Values.global.security.oauth.clientSecret | b64enc }}
  redirect_url: {{ .Values.global.security.oauth.redirectUrl | b64enc }}
  token_endpoint: {{ .Values.global.security.oauth.tokenEndpoint | b64enc }}
  auth_scope: {{ .Values.global.security.oauth.scope | b64enc }}
  token_lifetime: {{ .Values.global.security.oauth.tokenLifetime | b64enc }}
---
{{/* AWS KMS Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackpoint.fullname" . }}-kms-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    encryption.blackpoint.io/kms-key: alias/blackpoint-secrets
    secret.blackpoint.io/rotation-schedule: {{ .Values.global.security.secretRotation.schedule }}
    secret.blackpoint.io/last-rotated: {{ .Values.global.security.secretRotation.lastRotated }}
    audit.blackpoint.io/enabled: "true"
    monitoring.blackpoint.io/alert-on-access: "true"
type: Opaque
data:
  aws_access_key_id: {{ .Values.global.security.kms.accessKeyId | b64enc }}
  aws_secret_access_key: {{ .Values.global.security.kms.secretAccessKey | b64enc }}
  kms_key_id: {{ .Values.global.security.kms.keyId | b64enc }}
  aws_region: {{ .Values.global.security.kms.region | b64enc }}
  kms_endpoint: {{ .Values.global.security.kms.endpoint | b64enc }}
---
{{/* ChaosSearch Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackpoint.fullname" . }}-chaossearch-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    encryption.blackpoint.io/kms-key: alias/blackpoint-secrets
    secret.blackpoint.io/rotation-schedule: {{ .Values.global.security.secretRotation.schedule }}
    secret.blackpoint.io/last-rotated: {{ .Values.global.security.secretRotation.lastRotated }}
    audit.blackpoint.io/enabled: "true"
    monitoring.blackpoint.io/alert-on-access: "true"
type: Opaque
data:
  api_key: {{ .Values.global.security.chaosSearch.apiKey | b64enc }}
  api_secret: {{ .Values.global.security.chaosSearch.apiSecret | b64enc }}
  endpoint: {{ .Values.global.security.chaosSearch.endpoint | b64enc }}
  org_id: {{ .Values.global.security.chaosSearch.orgId | b64enc }}
  bucket_name: {{ .Values.global.security.chaosSearch.bucketName | b64enc }}
---
{{/* Confluent Cloud Credentials Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackpoint.fullname" . }}-confluent-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    encryption.blackpoint.io/kms-key: alias/blackpoint-secrets
    secret.blackpoint.io/rotation-schedule: {{ .Values.global.security.secretRotation.schedule }}
    secret.blackpoint.io/last-rotated: {{ .Values.global.security.secretRotation.lastRotated }}
    audit.blackpoint.io/enabled: "true"
    monitoring.blackpoint.io/alert-on-access: "true"
type: Opaque
data:
  sasl_username: {{ .Values.global.security.confluent.saslUsername | b64enc }}
  sasl_password: {{ .Values.global.security.confluent.saslPassword | b64enc }}
  bootstrap_servers: {{ .Values.global.security.confluent.bootstrapServers | b64enc }}
  security_protocol: {{ .Values.global.security.confluent.securityProtocol | b64enc }}
  ssl_endpoint: {{ .Values.global.security.confluent.sslEndpoint | b64enc }}
---
{{/* TLS Certificates Secret */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blackpoint.fullname" . }}-tls-certificates
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    encryption.blackpoint.io/kms-key: alias/blackpoint-secrets
    secret.blackpoint.io/rotation-schedule: {{ .Values.global.security.secretRotation.schedule }}
    secret.blackpoint.io/last-rotated: {{ .Values.global.security.secretRotation.lastRotated }}
    audit.blackpoint.io/enabled: "true"
    monitoring.blackpoint.io/alert-on-access: "true"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.security.tls.certificate | b64enc }}
  tls.key: {{ .Values.global.security.tls.privateKey | b64enc }}
  ca.crt: {{ .Values.global.security.tls.caCertificate | b64enc }}