{{/* Service template for BlackPoint Security Integration Framework */}}

{{/* Gateway Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-gateway
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.gateway.service.sslCertArn | quote }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "proxy-ssl,admin-ssl"
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.gateway.metrics.port | quote }}
spec:
  type: {{ .Values.gateway.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - port: 8000
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: 8443
      targetPort: proxy-ssl
      protocol: TCP
      name: proxy-ssl
    - port: 8001
      targetPort: admin
      protocol: TCP
      name: admin
    - port: 8444
      targetPort: admin-ssl
      protocol: TCP
      name: admin-ssl
    - port: {{ .Values.gateway.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    component: gateway

---
{{/* Collector Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-collector
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.collector.service.metricsPort | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.collector.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.collector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.collector.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    component: collector

---
{{/* Normalizer Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-normalizer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.normalizer.service.metricsPort | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.normalizer.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.normalizer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.normalizer.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    component: normalizer

---
{{/* Analyzer Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blackpoint.fullname" . }}-analyzer
  labels:
    {{- include "blackpoint.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.analyzer.service.metricsPort | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.analyzer.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.analyzer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.analyzer.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "blackpoint.selectorLabels" . | nindent 4 }}
    component: analyzer