# Normalizer Service Configuration
# Version: 1.0.0
# Purpose: Configuration for Silver tier event normalization service

service:
  name: normalizer
  version: 1.0.0
  environment: production
  log_level: info
  metrics_enabled: true

processing:
  # Processing timeout and retry configuration
  timeout: 5s
  max_retries: 3
  retry_backoff: 100ms
  batch_size: 100
  concurrent_processors: 10
  validation_rules:
    accuracy_threshold: 0.8
    field_validation: true
    pattern_matching: true

field_mapping:
  # Standard field mappings for security events
  standard_mappings:
    source_ip: src_ip
    destination_ip: dst_ip
    source_port: src_port
    destination_port: dst_port
    event_timestamp: event_time
    event_severity: severity
    event_category: category
    event_action: action
    user_id: user
    resource_id: resource

  # Required fields for validation
  required_fields:
    - event_type
    - event_time
    - src_ip
    - dst_ip
    - severity

  # Field length and encryption settings
  max_field_length: 4096
  field_encryption:
    enabled: true
    fields:
      - user
      - password
      - api_key
    algorithm: AES-256-GCM

transformation:
  # Transformation settings and timeouts
  timeout: 2s
  data_types:
    event_time: timestamp
    src_port: integer
    dst_port: integer
    severity: string
    protocol: string
    bytes: integer
    duration: float

  format_standardization:
    timestamp_format: RFC3339
    ip_format: IPv4
    case_sensitivity: lowercase
    number_format: decimal
    boolean_values:
      - "true"
      - "false"

  security_patterns:
    ip_validation: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
    port_validation: "^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$"
    severity_levels:
      - critical
      - high
      - medium
      - low
      - info

streaming:
  consumer:
    topic: bronze-events
    group_id: normalizer-group
    auto_offset_reset: latest
    max_poll_records: 500
    session_timeout_ms: 30000
    heartbeat_interval_ms: 10000

  producer:
    topic: silver-events
    compression_type: snappy
    batch_size: 100
    linger_ms: 10
    retries: 3
    retry_backoff_ms: 100

storage:
  type: chaossearch
  retention_days: 90
  index_pattern: silver-events-{yyyy.MM.dd}
  shards: 5
  replicas: 2
  refresh_interval: 1s
  security:
    encryption_at_rest: true
    audit_logging: true
    access_control: role_based

monitoring:
  metrics_interval: 10s
  health_check_interval: 30s
  tracing_enabled: true
  alert_thresholds:
    processing_latency: 5s
    error_rate: 0.01
    event_lag: 1000
    accuracy_threshold: 0.8
    field_validation_failures: 100
  audit_logging:
    enabled: true
    retention_days: 90
    include_fields:
      - event_id
      - transformation_type
      - validation_status
      - error_details