# Kubernetes Secrets v1.25.0
# Purpose: Store sensitive configuration data for BlackPoint Security Integration Framework
# Rotation Schedule:
# - OAuth credentials: 30 days
# - KMS credentials: 90 days
# - ChaosSearch credentials: 60 days
# - Confluent credentials: 45 days
# - TLS certificates: 90 days

---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
  namespace: blackpoint
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: auth
    secret.blackpoint.io/rotation: "30d"
  annotations:
    encryption.blackpoint.io/kms-key: "alias/blackpoint-secrets"
    secret.blackpoint.io/auto-rotation: "enabled"
    audit.blackpoint.io/enabled: "true"
    backup.blackpoint.io/enabled: "true"
type: Opaque
data:
  client_id: base64_encoded_client_id
  client_secret: base64_encoded_client_secret
  redirect_url: base64_encoded_redirect_url
  token_endpoint: base64_encoded_token_endpoint
  auth_endpoint: base64_encoded_auth_endpoint
  scope: base64_encoded_scope_list

---
apiVersion: v1
kind: Secret
metadata:
  name: kms-credentials
  namespace: blackpoint
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: encryption
    secret.blackpoint.io/rotation: "90d"
  annotations:
    encryption.blackpoint.io/kms-key: "alias/blackpoint-secrets"
    secret.blackpoint.io/auto-rotation: "enabled"
    audit.blackpoint.io/enabled: "true"
    backup.blackpoint.io/enabled: "true"
type: Opaque
data:
  aws_access_key_id: base64_encoded_access_key
  aws_secret_access_key: base64_encoded_secret_key
  kms_key_id: base64_encoded_key_id
  region: base64_encoded_region
  key_alias: base64_encoded_key_alias

---
apiVersion: v1
kind: Secret
metadata:
  name: chaossearch-credentials
  namespace: blackpoint
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: storage
    secret.blackpoint.io/rotation: "60d"
  annotations:
    encryption.blackpoint.io/kms-key: "alias/blackpoint-secrets"
    secret.blackpoint.io/auto-rotation: "enabled"
    audit.blackpoint.io/enabled: "true"
    backup.blackpoint.io/enabled: "true"
type: Opaque
data:
  api_key: base64_encoded_api_key
  api_secret: base64_encoded_api_secret
  endpoint: base64_encoded_endpoint
  bucket_name: base64_encoded_bucket
  index_prefix: base64_encoded_prefix
  retention_policy: base64_encoded_policy

---
apiVersion: v1
kind: Secret
metadata:
  name: confluent-credentials
  namespace: blackpoint
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: streaming
    secret.blackpoint.io/rotation: "45d"
  annotations:
    encryption.blackpoint.io/kms-key: "alias/blackpoint-secrets"
    secret.blackpoint.io/auto-rotation: "enabled"
    audit.blackpoint.io/enabled: "true"
    backup.blackpoint.io/enabled: "true"
type: Opaque
data:
  sasl_username: base64_encoded_username
  sasl_password: base64_encoded_password
  bootstrap_servers: base64_encoded_servers
  security_protocol: base64_encoded_protocol
  sasl_mechanism: base64_encoded_mechanism
  replication_factor: base64_encoded_factor

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: blackpoint
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: security
    secret.blackpoint.io/rotation: "90d"
  annotations:
    encryption.blackpoint.io/kms-key: "alias/blackpoint-secrets"
    secret.blackpoint.io/auto-rotation: "enabled"
    audit.blackpoint.io/enabled: "true"
    backup.blackpoint.io/enabled: "true"
type: kubernetes.io/tls
data:
  tls.crt: base64_encoded_certificate
  tls.key: base64_encoded_private_key
  ca.crt: base64_encoded_ca_certificate