# Kubernetes StorageClass configuration for BlackPoint Security Integration Framework
# Version: v1.25+
# Dependencies:
# - storage.k8s.io/v1 (v1.25+)
# - aws-ebs-csi-driver (v1.12+)

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blackpoint-high-performance
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    kubernetes.io/description: "BlackPoint Security Integration Framework storage classes for tiered data storage"
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: security-integration-framework
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iopsPerGB: "3000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: ${aws_kms_key_id}
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - noatime
  - nodiscard
  - defaults
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blackpoint-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    kubernetes.io/description: "BlackPoint Security Integration Framework storage classes for tiered data storage"
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: security-integration-framework
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iopsPerGB: "1000"
  throughput: "125"
  encrypted: "true"
  kmsKeyId: ${aws_kms_key_id}
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blackpoint-archive
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    kubernetes.io/description: "BlackPoint Security Integration Framework storage classes for tiered data storage"
  labels:
    app.kubernetes.io/name: blackpoint
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: security-integration-framework
provisioner: ebs.csi.aws.com
parameters:
  type: st1
  encrypted: "true"
  kmsKeyId: ${aws_kms_key_id}
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true